name: Docker Deploy CD

on:
  workflow_run:
    workflows:
      - Docker Image CI
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Tailscale network
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
        
      - name: Trigger webhook to deploy
        run: curl -X POST ${{ secrets.WEBHOOK_URL }}
